# Generated by Django 5.1.2 on 2024-11-07 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0002_alter_vehiculo_options_alter_vehiculo_marca'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'permissions': [('visualizar_catalogo', 'Puede ver el catálogo de vehículos'), ('add_vehiculomodel', 'Puede Agregar Nuevos Vehiculos')]},
        ),
    ]
